-- Migration SQL for RBAC baseline (Postgres)

CREATE TABLE IF NOT EXISTS "Role" (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Permission" (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "RolePermission" (
  id SERIAL PRIMARY KEY,
  "roleId" INTEGER NOT NULL REFERENCES "Role"(id) ON DELETE CASCADE,
  "permissionId" INTEGER NOT NULL REFERENCES "Permission"(id) ON DELETE CASCADE,
  "branchId" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  "fullName" TEXT,
  password TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "UserRole" (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  "roleId" INTEGER NOT NULL REFERENCES "Role"(id) ON DELETE CASCADE,
  "branchId" INTEGER NULL
);
